export const submissions = [
    {
        id: "JESAM-2025-128",
        title: "AI-Powered Learning Analytics in Higher Education",
        author: "John Doe",
        status: "Under Review",
        similarity: 12,
        date: "May 24, 2025",
    },
    {
        id: "JESAM-2025-127",
        title: "Green Supply Chain Management Practices",
        author: "Maria Santos",
        status: "Revision Required",
        similarity: 18,
        date: "May 23, 2025",
    },
    {
        id: "JESAM-2025-126",
        title: "Blockchain Technology in Financial Services",
        author: "Michael Lee",
        status: "Accepted",
        similarity: 9,
        date: "May 21, 2025",
    },
    {
        id: "JESAM-2025-125",
        title: "The Impact of Social Media on Student Performance",
        author: "Sarah Johnson",
        status: "Rejected",
        similarity: 32,
        date: "May 20, 2025",
    },
    {
        id: "JESAM-2025-124",
        title: "Sustainable Urban Development Strategies",
        author: "David Brown",
        status: "Under Review",
        similarity: 14,
        date: "May 19, 2025",
    },
];

export const reviewers = [
    {
        id: "rev-1",
        name: "Dr. Elena Hovart",
        email: "e.hovart@stanford.edu",
        initials: "EH",
        affiliation: "Stanford University",
        location: "Palo Alto, CA",
        expertise: ["AI Ethics", "NLP"],
        active: 3,
        rating: 5,
        status: "Active",
    },
    {
        id: "rev-2",
        name: "Prof. Marcus Chen",
        email: "m.chen@mit.edu",
        initials: "MC",
        affiliation: "MIT Research Lab",
        location: "Cambridge, MA",
        expertise: ["Quantum Computing"],
        active: 0,
        rating: 4,
        status: "On Leave",
    },
    {
        id: "rev-3",
        name: "Dr. Sarah Lundt",
        email: "sarah.l@ox.ac.uk",
        initials: "SL",
        affiliation: "University of Oxford",
        location: "Oxford, UK",
        expertise: ["Bioinformatics", "Genomics"],
        active: 5,
        rating: 5,
        status: "Active",
    },
    {
        id: "rev-4",
        name: "Dr. Julian Smith",
        email: "jsmith@ethz.ch",
        initials: "JS",
        affiliation: "ETH Zurich",
        location: "Zurich, Switzerland",
        expertise: ["Renewable Energy", "Grid Systems"],
        active: 2,
        rating: 4,
        status: "Active",
    },
];

export const users = [
    {
        id: "user-1",
        name: "Sarah Jenkins",
        subtitle: "Department of Physics",
        email: "sarah.jenkins@university.edu",
        role: "Administrator",
        canSubmit: true,
        lastActive: "2 hours ago",
        avatar: "",
        initials: "SJ",
    },
    {
        id: "user-2",
        name: "Dr. Marcus Thorne",
        subtitle: "Biological Sciences",
        email: "m.thorne@research.org",
        role: "Reviewer",
        canSubmit: false,
        lastActive: "Yesterday, 14:30",
        initials: "MT",
    },
    {
        id: "user-3",
        name: "Elena Rostova",
        subtitle: "History Faculty",
        email: "elena.r@university.edu",
        role: "Author",
        canSubmit: true,
        lastActive: "Oct 12, 2026",
        initials: "EL",
    },
];
