/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppArticlesIndexRouteImport } from './routes/_app/articles/index'
import { Route as AppArticlesCreateRouteImport } from './routes/_app/articles/create'
import { Route as AppArticlesArticleIdRouteImport } from './routes/_app/articles/$articleId'
import { Route as AppArticlesAuthorArticleidRouteImport } from './routes/_app/articles/author.$articleid'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesIndexRoute = AppArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesCreateRoute = AppArticlesCreateRouteImport.update({
  id: '/articles/create',
  path: '/articles/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesArticleIdRoute = AppArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesAuthorArticleidRoute =
  AppArticlesAuthorArticleidRouteImport.update({
    id: '/articles/author/$articleid',
    path: '/articles/author/$articleid',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/articles/create': typeof AppArticlesCreateRoute
  '/articles/': typeof AppArticlesIndexRoute
  '/articles/author/$articleid': typeof AppArticlesAuthorArticleidRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/articles/create': typeof AppArticlesCreateRoute
  '/articles': typeof AppArticlesIndexRoute
  '/articles/author/$articleid': typeof AppArticlesAuthorArticleidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/_app/articles/create': typeof AppArticlesCreateRoute
  '/_app/articles/': typeof AppArticlesIndexRoute
  '/_app/articles/author/$articleid': typeof AppArticlesAuthorArticleidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/$articleId'
    | '/articles/create'
    | '/articles/'
    | '/articles/author/$articleid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/$articleId'
    | '/articles/create'
    | '/articles'
    | '/articles/author/$articleid'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/articles/$articleId'
    | '/_app/articles/create'
    | '/_app/articles/'
    | '/_app/articles/author/$articleid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/articles/': {
      id: '/_app/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof AppArticlesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/articles/create': {
      id: '/_app/articles/create'
      path: '/articles/create'
      fullPath: '/articles/create'
      preLoaderRoute: typeof AppArticlesCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/articles/$articleId': {
      id: '/_app/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof AppArticlesArticleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/articles/author/$articleid': {
      id: '/_app/articles/author/$articleid'
      path: '/articles/author/$articleid'
      fullPath: '/articles/author/$articleid'
      preLoaderRoute: typeof AppArticlesAuthorArticleidRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppArticlesArticleIdRoute: typeof AppArticlesArticleIdRoute
  AppArticlesCreateRoute: typeof AppArticlesCreateRoute
  AppArticlesIndexRoute: typeof AppArticlesIndexRoute
  AppArticlesAuthorArticleidRoute: typeof AppArticlesAuthorArticleidRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppArticlesArticleIdRoute: AppArticlesArticleIdRoute,
  AppArticlesCreateRoute: AppArticlesCreateRoute,
  AppArticlesIndexRoute: AppArticlesIndexRoute,
  AppArticlesAuthorArticleidRoute: AppArticlesAuthorArticleidRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
